---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rails-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rails-container
  template:
    metadata:
      labels:
        name: rails-container
    spec:
      containers:
        - name: rails-container
          image: ryangrush/blog_app:2.0.0
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
            - name: SECRET_KEY_BASE
              value: "88d24294e8de572f8526f0f0fcc51c0a857b58aee01182303c8bed8fae8646831a350f323e1d090c43055e6466275500006bc312ea0ab287cc0cb611619666fb"