---
apiVersion: v1
kind: Service
metadata:
  name: rails-service
  labels:
    name: rails-service
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    name: rails-deployment
  type: NodePort